version: '3.8'

services:
  app:
    build: .
    container_name: pedido-atendimento-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pedido_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    container_name: postgres_pedido
    environment:
      POSTGRES_DB: pedido_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

